### ISSUE TITLE
BGM再生中に保存したセーブデータを読み込むとエラーが発生する

### ISSUE THREAD

**Issue by 0tarof** [krkrz/kag3_ham#1]
タイトルの通りですが、BGM再生中に保存したセーブデータを読み込む際、
下記の行でエラーが発生します。

https://github.com/krkrz/kag3_ham/blob/157422e1c9ba97e125b9306955e5229bcd55957d/data/system/Ham/Base/HackKag3.tjs#L194

MercuryBlueクラスに指定されているフラグが無いことによるものと思いますが、ご確認お願い致します。

**Comment by HirohikoFujikawa** [comment]
ご連絡ありがとうございました。
当該の不具合につき修正しました。
今後ともよろしくお願いします。
