### ISSUE TITLE
吉里吉里Z v1.3.0.4以降で、xp3から起動しようとすると、DLLが読み込めず起動できない

### ISSUE THREAD

**Issue by 0tarof** [krkrz/kag3_ham#2]
仕様変更の詳細は確認できていませんが、吉里吉里Z v1.3.0.4以降から、xp3内にあるDLLを読み込めなくなっています。

そのため、
https://github.com/krkrz/kag3_ham/blob/fff49152b3376a21f26ef6efdec76263d82e7938/data/system/Ham/Ham.tjs#L34
上記行でエラーが発生し、ゲームが開始できないようです。

実パス上に上`ktl_local_files.dll`を配置し、上記ファイル内のパス指定を変更することで読み込みはできるようです。

**Comment by jin1016** [comment]
https://github.com/krkrz/krkrz/issues/110
本体のこの修正のデグレードです。
リポジトリ上は修正されていますが、修正されたバイナリはまだリリースされていません。
なお、吉里吉里Z本体の64bit対応に伴い、32bit/64bit両対応化することが出来なくなるためxp3内にdllを入れるのは非推奨になっています。

**Comment by 0tarof** [comment]
仰るとおり64bit化の時を考えると実パス上に配置するのが良さそうですので、その形で対応することに致します。
ご回答ありがとうございました。

**Comment by HirohikoFujikawa** [comment]
dll読み込みに関するコードを修正し、配布アーカイブに含まれていたdllを削除しました。
これにより一部機能に影響がありますが、同機能はプラグインの別途導入及びHam拡張設定ファイルの編集により復帰可能です。
詳細はコミットログを参照してください。
